<head>
<title>User Documentation</title>
<style>
h2{
  text-decoration: underline;
}

</style>
</head>

<body>

<table border="1" width = "1650" height = "1000" cellpadding = "15" cellspacing = "10" bgcolor="#bedbeb">

<tr bgcolor="#FFFFFF">
<td height = "20%" bgcolor = "#3c94c3" valign = "bottom"><font size ="40" font face = "courier"> <p align = "right"><font color="183a4e">Photo</font><font color="#FFFFFF">synthesis</p></font></td>
</tr>



<tr bgcolor="#FFFFFF">

<td height = "3%" cellpadding="30" cellspacing = "30">|| <a href="addphoto.jsp">Add Photo</a> | 

<a href="PictureBrowse.jsp">Search Photos</a> | <a href="groups.jsp">Groups</a> |
<%
if(session.getAttribute("userName").toString().equals("admin")){
out.println("<a href=\"analysis.jsp\">Analysis</a> | ");
}
%> <a href="logout.jsp">Logout</a> | <a href="help.jsp">Help</a> ||</td>

</tr>

<tr bgcolor="#FFFFFF">
<td>

<h1>User Documentation</h1>
<h2>How to Install:</h2>

<ol>
  <li>Run the required swl scripts:
  <ol type='a'>
     <li>setup_w2016.sql
     <li>sequences.sql
     <li>viewed.sql
     <li>image_cube.sql
     <li>indexes.sql, indexes2.sql, indexes3.sql, indexes4.sql
  </ol>
  <li>Put all the html and jsp into the same folder (eg. proj1) inside catalina/webapps
  <li>Inside this folder create a folder 'WEB-INF' and then a folder 'lib' within that. Place both jar files (ojdbc6.jar and commons-fileupload-1.0.jar) in 'lib'
  <li>Start using the website by going to /auth.html using the required url information for your lab machine in your browser
  <li>Input a valid sqlplus account and enjoy!
</ol>


<h2>Module Information</h2>

<h3>User Management Module</h3>
<p>After entering sqlplus information you will be directed to a page to either signin or signup. If you already have valid credentials for the webpage enter your username and password. Otherwise, hit sign-up and enter your information. After signing up you will be directed to the same page as if you were logging in.</p>

<h3>Security Module</h3>
<p>On your home page (success.jsp) you will be able to add photos or create groups. When you hit the Groups button you can create a group with a unique name and add users to it. Groups created in this manner will show up when you are adding photos, allowing you to share them with just the people in that group. By default, a photo can be seen by anyone (Public) or just by yourself (Private). If you try to view a picture you do not have permission to view, you are directed to an error page.<p>

<h3>Uploading Module</h3>
<p>When selecting the Add Photo option on your home page you are directed to a page that allows you to upload any number of photographs along with information about them. This includes subject, date, location, description and who can see that picture(s). Pictures uploaded at the same time are given the same information except for their photo id which is unique.</p>

<h3>Display Module</h3>
<p>On various parts of the website you will see thumbnails that have been generated by uploaded photos. Upon clicking on one of these thumbnails you are directed to a page that allows you to view that picture in its original size. If you do not have permission to view the image you are redirected to an error page. If you are the owner of that picture you are able to edit the photo changing its information or even deleting it. If the user is an admin then they are able to see any picture on the website regardless of permissions. One of the places that you can see thumbnails is in the form of the Top 5 Most Popular section on your home page. This displays photos which have been seen by the most unique viewers (each user only counts once). If there are any ties, all results are shown so sometimes there may be more than 5 thumbnails shown. If you do not have permission to see a photo you are still able to see the thumbnail, but when clicking on it you are directed to an error page.</p>

<h3>Search Module</h3>
<p>When clicking on the Search Photos button you are directed a page that has a table of photos that you are able to see. You are also allowed to narrow your search given serach terms and date ranges. You are allowed to order these images by most recent, oldest and by relevancy given by the scoring function (6*score(subject) + 3*score(place) + score(description). When the admin is preforming searches they are not limited by permissions.</p>

<h3>Data Analysis Module</h3>
<p>When logged in as an admin you are able to see the Analysis button. This brings you to a page where you are able to decide what type of report you want based off of a mixture of usernames, subject and dateranges. After clicking Generate you are presented with a report which contains ALL the information given the options chosen. The user is then able to narrow the report based off of the options they chose. If any option is left blank the system will not narrow by it and will instead show ALL data for that option. The user is also able to 'drill down' and 'generalize' on a time hierarchy of yearly, monthly and weekly. If the user wants to generate a new report all they have to do is hit the Restart button.</p>

